services:
  db:
    image: postgres:15-alpine
    container_name: telegram_profile_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ./bot
    container_name: telegram_profile_bot
    env_file:
      - ./bot/.env
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: telegram_profile_backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: telegram_profile_frontend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: telegram_profile_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  pgdata: