- hosts: project_server
  become: yes
  vars:
    domain_name: "friedox.online"
    email: "dvzvidrin48@gmail.com"
    project_dir: "/root/test-task-tg-profile"
    ssl_dir: "{{ project_dir }}/ssl"
    certbot_webroot: "{{ project_dir }}/certbot/www"
    frontend_dir: "{{ project_dir }}/frontend"
    backend_dir: "{{ project_dir }}/backend"
    bot_dir: "{{ project_dir }}/bot"
    nginx_container: "telegram_profile_nginx"

  tasks:
    - name: Установка зависимостей
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - certbot
          - python3-certbot-nginx
          - openssl
        state: present

    - name: Добавляем Docker GPG ключ
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавляем Docker репозиторий
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Устанавливаем Docker и Docker Compose
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Убеждаемся, что Docker daemon запущен и в автозагрузке
      service:
        name: docker
        state: started
        enabled: true

    - name: Клонируем проект
      git:
        repo: "https://github.com/Friedox/test-task-tg-profile.git"
        dest: "{{ project_dir }}"
        version: "main"
        force: yes
        accept_hostkey: yes

    - name: Копируем backend .env
      copy:
        src: ../backend/.env
        dest: "{{ backend_dir }}/.env"
        mode: '0600'

    - name: Копируем frontend .env
      copy:
        src: ../frontend/.env
        dest: "{{ frontend_dir }}/.env"
        mode: '0600'

    - name: Копируем bot .env
      copy:
        src: ../bot/.env
        dest: "{{ bot_dir }}/.env"
        mode: '0600'

    - name: Копируем общий .env
      copy:
        src: ../.env
        dest: "{{ project_dir }}/.env"
        mode: '0600'

    - name: Создаем каталог для webroot Let's Encrypt
      file:
        path: "{{ certbot_webroot }}"
        state: directory
        mode: '0755'

    - name: Запускаем docker compose без nginx для SSL получения
      command: docker compose up -d --build db backend bot frontend
      args:
        chdir: "{{ project_dir }}"

    - name: Получаем/обновляем SSL сертификат от Let's Encrypt (webroot)
      command: >
        certbot certonly --webroot
        --webroot-path {{ certbot_webroot }}
        -d {{ domain_name }} -d www.{{ domain_name }}
        --email {{ email }}
        --agree-tos --non-interactive --force-renewal

    - name: Создаем симлинки на сертификаты для Nginx
      file:
        src: "/etc/letsencrypt/live/{{ domain_name }}/{{ item }}"
        dest: "{{ ssl_dir }}/{{ item }}"
        state: link
        force: true
      loop:
        - fullchain.pem
        - privkey.pem

    - name: Запускаем весь проект с nginx
      command: docker compose up -d --build
      args:
        chdir: "{{ project_dir }}"

    - name: Настраиваем автоматическое обновление сертификатов через cron
      cron:
        name: "Auto renew SSL and restart nginx"
        minute: "0"
        hour: "3"
        job: "docker compose stop nginx && certbot renew --webroot --webroot-path {{ certbot_webroot }} && docker compose start nginx"
