- hosts: project_server
  become: yes
  vars:
    domain_name: "friedox.online"
    email: "dvzvidrin48@gmail.com"
    project_dir: "/root/test-task-tg-profile"
    ssl_dir: "{{ project_dir }}/certbot/conf"
    certbot_webroot: "{{ project_dir }}/certbot/www"
    frontend_dir: "{{ project_dir }}/frontend"
    backend_dir: "{{ project_dir }}/backend"
    bot_dir: "{{ project_dir }}/bot"

  tasks:

    - name: Установка системных пакетов
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Добавляем Docker GPG ключ
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавляем Docker репозиторий
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Устанавливаем Docker и Docker Compose
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Убеждаемся, что Docker daemon запущен и в автозагрузке
      service:
        name: docker
        state: started
        enabled: true

    - name: Клонируем проект
      git:
        repo: "https://github.com/Friedox/test-task-tg-profile.git"
        dest: "{{ project_dir }}"
        version: "main"
        force: yes
        accept_hostkey: yes

    - name: Копируем backend .env
      copy:
        src: ../backend/.env
        dest: "{{ backend_dir }}/.env"
        mode: '0600'

    - name: Копируем frontend .env
      copy:
        src: ../frontend/.env
        dest: "{{ frontend_dir }}/.env"
        mode: '0600'

    - name: Копируем bot .env
      copy:
        src: ../bot/.env
        dest: "{{ bot_dir }}/.env"
        mode: '0600'

    - name: Копируем общий .env
      copy:
        src: ../.env
        dest: "{{ project_dir }}/.env"
        mode: '0600'

    - name: Создаем каталог для webroot Let's Encrypt
      file:
        path: "{{ certbot_webroot }}"
        state: directory
        mode: '0755'

    - name: Создаем каталог для сертификатов Let's Encrypt
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '0755'

    - name: Стоп docker compose перед получением сертификата
      command: docker compose down
      args:
        chdir: "{{ project_dir }}"

    - name: Запускаем nginx для верификации
      command: docker compose up -d nginx
      args:
        chdir: "{{ project_dir }}"

    - name: Получаем/обновляем SSL сертификат от Let's Encrypt через Docker Certbot
      command: >
        docker run --rm
        -v {{ ssl_dir }}:/etc/letsencrypt
        -v {{ certbot_webroot }}:/var/www/certbot
        certbot/certbot certonly --webroot
        --webroot-path /var/www/certbot
        -d {{ domain_name }} -d www.{{ domain_name }}
        --email {{ email }}
        --agree-tos --non-interactive --force-renewal

    - name: Запускаем docker compose со всеми сервисами
      command: docker compose up -d --build
      args:
        chdir: "{{ project_dir }}"

    - name: Настраиваем cron на авто renew сертификатов + рестарт nginx
      cron:
        name: "Auto renew SSL certbot + nginx restart"
        minute: "0"
        hour: "3"
        job: "docker run --rm -v {{ ssl_dir }}:/etc/letsencrypt -v {{ certbot_webroot }}:/var/www/certbot certbot/certbot renew --webroot --webroot-path /var/www/certbot && docker compose restart nginx"
