- hosts: project_server
  become: yes
  vars:
    project_dir: "/root/test-task-tg-profile"
    ssl_dir: "{{ project_dir }}/ssl"
    frontend_dir: "{{ project_dir }}/frontend"
    backend_dir: "{{ project_dir }}/backend"
    bot_dir: "{{ project_dir }}/bot"
    domains: "friedox.online"
    email: "dvzvidrin48@gmail.com"

  tasks:
    - name: Обновляем APT и ставим зависимости
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - certbot
          - python3-certbot-nginx
          - openssl
        state: present

    - name: Добавляем Docker GPG ключ
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавляем Docker репозиторий
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Устанавливаем Docker и Docker Compose CLI (plugin)
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Убеждаемся, что Docker daemon запущен и в автозагрузке
      service:
        name: docker
        state: started
        enabled: true

    - name: Клонируем проект
      git:
        repo: "https://github.com/Friedox/test-task-tg-profile.git"
        dest: "{{ project_dir }}"
        version: "main"
        force: yes
        accept_hostkey: yes

    - name: Копируем backend .env
      copy:
        src: ../backend/.env
        dest: "{{ backend_dir }}/.env"
        mode: '0600'

    - name: Копируем frontend .env
      copy:
        src: ../frontend/.env
        dest: "{{ frontend_dir }}/.env"
        mode: '0600'

    - name: Копируем bot .env
      copy:
        src: ../bot/.env
        dest: "{{ bot_dir }}/.env"
        mode: '0600'

    - name: Копируем общий .env
      copy:
        src: ../.env
        dest: "{{ project_dir }}/.env"
        mode: '0600'

    - name: Создаем папку для Let's Encrypt
      file:
        path: /etc/letsencrypt
        state: directory
        mode: '0755'

    - name: Получаем SSL сертификаты через Certbot (только если их нет)
      command: |
        certbot certonly --nginx --non-interactive --agree-tos \
        -m {{ email }} \
        -d {{ domains }} \
        --keep-until-expiring \
        --dry-run
      ignore_errors: yes
      register: certbot_dry_run
      changed_when: false

    - name: Получаем SSL сертификаты через Certbot (реальный запуск)
      command: |
        certbot certonly --nginx --non-interactive --agree-tos \
        -m {{ email }} \
        -d {{ domains }} \
        --keep-until-expiring
      when: certbot_dry_run is failed

    - name: Добавляем cron для обновления сертификатов
      cron:
        name: "Certbot renewal"
        user: root
        job: "certbot renew --quiet --post-hook 'docker restart telegram_profile_nginx'"
        minute: "0"
        hour: "3"
        weekday: "0"

    - name: Запускаем docker compose up -d --build
      command: docker compose up -d --build
      args:
        chdir: "{{ project_dir }}"