- hosts: django_server
  become: yes
  vars:
    project_dir: "/home/ubuntu/test-task-django-stripe"
    ssl_dir: "{{ project_dir }}/ssl"

  tasks:
    - name: Update APT and install dependencies
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nginx
          - certbot
          - python3-certbot-nginx
          - openssl
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Clone project from GitHub
      git:
        repo: "git@github.com:Friedox/test-task-django-stripe.git"
        dest: "{{ project_dir }}"
        version: "main"
        force: yes
        accept_hostkey: yes
        key_file: "/root/.ssh/id_ed25519"

    - name: Copy .env file to server
      copy:
        src: ../.env
        dest: "{{ project_dir }}/.env"
        mode: '0600'

    - name: Ensure SSL directory exists
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '0755'

    - name: Generate a self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout {{ ssl_dir }}/nginx-selfsigned.key
        -out {{ ssl_dir }}/nginx-selfsigned.crt
        -subj "/C=US/ST=State/L=City/O=Company/CN=147.45.69.155"
      args:
        creates: "{{ ssl_dir }}/nginx-selfsigned.crt"

    - name: Start Docker services
      command: docker compose up -d --build
      args:
        chdir: "{{ project_dir }}"

    - name: Set up automatic SSL renewal
      cron:
        name: "Renew SSL certificates"
        job: "certbot renew --quiet || systemctl reload nginx"
        minute: "0"
        hour: "0"